max_width = 80
wrap_comments = true
format_code_in_doc_comments = true
format_strings = true
merge_imports = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
struct_field_align_threshold = 20
ignore = []
